### ISSUE TITLE
Not working.

### ISSUE THREAD

**Issue by ghost** [nick132/Anti-AFK#1]
I'm playing Sea of Thieves, installed the required libraries and ran the script. It told me to toggle on and I did, nothing is happening. Is it supposed to be doing this or what?

**Comment by nick132** [comment]
Basically the way the script works is by moving the mouse a little bit
every once In a while.  I don't play that game you're trying to use it on
so I am not sure what is required to stop an afk kick.  If you have to move
around or jump to stop AFK kicks, this script won't work for that game.
